# Generated by Django 4.1.2 on 2023-11-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_annotation_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='text',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='annotations',
            field=models.ManyToManyField(blank=True, to='api.annotation'),
        ),
    ]
